# -*- coding: utf-8 -*-
"""AA_Clase2_Alderete_Tomás.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hV1fsIRN-syiuW3ZlCbi3DNJhs8QwhM6

3. Instancia de  Evaluación Espacio de entrega de tarea:
En esta instancia de evaluación te pedimos que puedas poner en juego lo que has aprendido hasta este momento. Recordá que siempre podrás volver a la teoría presentada en esta clase o hacer las preguntas pertinentes en los encuentros sincrónicos o las tutorías presenciales.

Es importante tener en cuenta que para aprobar esta instancia deberás:

-               Entregar en tiempo y forma

-               Realizar un 60% de la actividad correctamente.

-               Cumplir con las consignas

-               Cumplir con el formato requerido.

La nota mínima para aprobar la tarea es 6.

En el emocionante campo de la Ciencia de Datos, uno de los primeros pasos es la importación y manipulación efectiva de datos. La librería PANDAS en Python es una herramienta esencial para llevar a cabo esta tarea, ya que proporciona funciones y estructuras de datos que permiten la limpieza, transformación y análisis de datos de manera eficiente.

Imaginemos que eres un científico de datos que trabaja en un proyecto de análisis de mercado para una empresa de comercio electrónico. Tu objetivo es recopilar, procesar y analizar datos de ventas que provienen de diferentes fuentes en varios formatos. Para lograrlo, debes diseñar un proceso de importación de datos utilizando PANDAS.

Datos de Prueba:

1. Archivo CSV (Comma-Separated Values): Tienes un archivo llamado "ventas.csv" que contiene información sobre las ventas de productos. Cada fila representa una venta y contiene varias columnas con los datos sobre las ventas.

 2. Archivo JSON (JavaScript Object Notation): También tienes un archivo llamado "clientes.json" con datos de los clientes que realizaron las compras. Cada objeto JSON representa un cliente y contiene sus datos.



3. Hoja de Cálculo Excel: Existe un archivo llamado "inventario.xlsx" con información sobre el inventario de productos. La hoja de cálculo contiene varias columnas con datos sobre los productos.

    

Tu tarea es utilizar la librería PANDAS para importar estos datos desde los diferentes formatos (CSV, JSON y Excel), combinarlos en una estructura de datos adecuada y realizar las siguientes acciones:

1. Cargar los datos de ventas desde el archivo CSV y mostrar una vista previa de las primeras filas.

2. Cargar los datos de clientes desde el archivo JSON y mostrar la cantidad total de clientes.

3. Cargar los datos de inventario desde la hoja de cálculo Excel y calcular el promedio de stock disponible para todos los productos.



Al abordar este problema, estarás demostrando tu capacidad para importar, combinar y realizar operaciones básicas de análisis de datos utilizando PANDAS en el contexto del Aprendizaje Automático. ¡Manos a la obra!

En el próximo encuentro sincrónico haremos intercambio de ideas sobre cómo resolver esta actividad.
"""

import pandas as pd
dat_csv = pd.read_csv('ventas.csv', encoding = "ISO-8859-1")
dat_csv.head()

clientes_json = pd.read_json('clientes.json')
print(clientes_json)


a = len(clientes_json)
print("\n") #Espacio en blanco
print("La cantidad de registros son:", a)

tabla = pd.read_excel('inventario.xlsx')
print(tabla)
print("\n") #Espacio en blanco
print("El promedio del stock disponible es: ", tabla['stock'].mean())