# -*- coding: utf-8 -*-
"""Copia de AA_CLASE3_TEORIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ca0Co-yBQOuHgeUcwPeo1jMi1-eZQ8f

Tareas a realizar:

1.    Cargar el conjunto de datos en una estructura adecuada para su manipulación.

2.   Crear un gráfico de dispersión para visualizar las relaciones entre los pares de características numéricas `mpg` y `weight`.

3.   Generar un histograma del consumo de combustible (`mpg`) para analizar su distribución.

4.   Graficar un diagrama de caja (boxplot) de las características `cylinders` y `origin` para identificar posibles valores atípicos.

5.   Realizar un gráfico de barras que muestre la distribución de automóviles según su año de modelo (`model_year`) y origen (`origin`).

Recuerda que la visualización de datos es una etapa esencial en el proceso de Aprendizaje Automático, ya que proporciona intuiciones valiosas que pueden guiar decisiones posteriores en la construcción y evaluación de modelos predictivos. Utiliza Matplotlib para crear gráficos claros y etiquetados que ayuden en el análisis de los datos.
"""

# 1 - Cargar el conjunto de Datos.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dat_csv = pd.read_csv('Automobile.csv', encoding = "ISO-8859-1")
dat_csv.head()

# 2 - Crear un grafico de disperción entre mgp y weight.

plt.scatter(dat_csv['mpg'], dat_csv['weight'])
plt.xlabel('mpg')
plt.ylabel('weight')
plt.show()

#3 - Generar un histograma del consumo de combustible (`mpg`) para analizar su distribución.

plt.hist(dat_csv['mpg'])
plt.xlabel('mpg')
plt.ylabel('Cantidad')
plt.show()

# 4 - Boxplot de cylinders y de origin

plt.figure(figsize=(10, 6))
sns.boxplot(data=dat_csv, x='origin', y='cylinders', palette='viridis')

# 5 - Gráfico de barras con la  distribución año de modelo (`model_year`) y origen (`origin`).

sns.countplot(x="model_year", hue="origin", data=dat_csv)
plt.title('Distrinbución según año y origen')
plt.xlabel('Año de modelo y Origen')
plt.ylabel('Cantidad')
plt.show()