# -*- coding: utf-8 -*-
"""MineriaDatos_U2_Clase2_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csWH99vNCXgBblQPukKiMcGHbUkMS6sb

|# 🔬 Minería de Datos — Unidad 2 · Clase 2
## Laboratorio: Tipos de Datos y Estadística Descriptiva con Pandas

**Tecnicatura en Cs de Datoa e IA — Politécnico Malvinas Argentinas — 2026**

---

### Objetivos del laboratorio

- Inspeccionar tipos de datos con `.dtypes` e `.info()`
- Convertir tipos con `.astype()` para optimizar memoria y semántica
- Calcular estadísticas descriptivas: media, mediana, moda, varianza, IQR
- Visualizar distribuciones con histogramas y boxplots
- Detectar outliers usando la regla del IQR

### Dataset
Trabajamos con el **Titanic** — un clásico del análisis de datos con variables de todos los tipos.

| Columna | Descripción | Tipo estadístico |
|---------|------------|------------------|
| PassengerId | ID único del pasajero | Nominal (ID) |
| Survived | Sobrevivió (0=No, 1=Sí) | Nominal binario |
| Pclass | Clase del pasaje (1, 2, 3) | Ordinal |
| Name | Nombre completo | Nominal |
| Sex | Sexo | Nominal |
| Age | Edad en años | Continua |
| SibSp | Hermanos/cónyuge a bordo | Discreta |
| Parch | Padres/hijos a bordo | Discreta |
| Ticket | Número de ticket | Nominal |
| Fare | Precio del pasaje | Continua |
| Cabin | Número de cabina | Nominal |
| Embarked | Puerto de embarque (C, Q, S) | Nominal |

---
## 📦 Sección 1: Setup e importación del dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de visualizaciones
plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False
sns.set_theme(style='whitegrid', palette='Set2')

print('Librerías cargadas correctamente.')

# Cargar dataset Titanic
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

print(f'Dataset cargado exitosamente.')
print(f'Dimensiones: {df.shape[0]} filas x {df.shape[1]} columnas')

# Vista previa de las primeras filas
df.head()

# Vista previa de las últimas filas
df.tail(3)

# Columnas disponibles
print('Columnas:', list(df.columns))
print()

# Valores nulos por columna
nulos = df.isnull().sum()
pct_nulos = (df.isnull().mean() * 100).round(1)

resumen_nulos = pd.DataFrame({
    'Nulos': nulos,
    'Porcentaje (%)': pct_nulos
}).query('Nulos > 0')

print('Columnas con valores nulos:')
print(resumen_nulos)

"""---
## 🔍 Sección 2: Explorar tipos de datos

> **Recordar:** el tipo en Pandas (`int64`, `float64`, `object`) no siempre coincide con el tipo estadístico (nominal, ordinal, discreta, continua).
"""

# Tipos de datos asignados automáticamente por Pandas
df.dtypes

# .info() — vista completa: tipos, no-nulos, memoria
df.info()

# Memoria usada por el DataFrame completo

memoria_mb = df.memory_usage(deep=True).sum() / 1024**2
print(f'Memoria total: {memoria_mb:.3f} MB')

"""### 🤔 Reflexión: ¿El tipo de dato coincide con el tipo estadístico?

Completá la tabla con tu análisis:

| Columna | dtype Pandas | Tipo estadístico | ¿El dtype es adecuado? |
|---------|-------------|-------------------|------------------------|
| PassengerId | int64 | ??? | ??? |
| Survived | int64 | ??? | ??? |
| Pclass | int64 | ??? | ??? |
| Sex | object | ??? | ??? |
| Age | float64 | ??? | ??? |
| Fare | float64 | ??? | ??? |

---
## 🔄 Sección 3: Convertir tipos con `.astype()`

Vamos a convertir columnas para que reflejen correctamente su tipo estadístico y para optimizar el uso de memoria.
"""

# Memoria ANTES de convertir
memoria_antes = df.memory_usage(deep=True).sum() / 1024**2
print(f'Memoria antes: {memoria_antes:.3f} MB')
print()
print('Tipos actuales:')
print(df.dtypes)

# Convertir tipos

# Survived: int64 -> bool (es binario: True/False)
df['Survived'] = df['Survived'].astype(bool)

# Pclass: int64 -> category (es ordinal: 1 < 2 < 3)
df['Pclass'] = df['Pclass'].astype('category')

# Sex: object -> category (pocos valores únicos)
df['Sex'] = df['Sex'].astype('category')

# Embarked: object -> category
df['Embarked'] = df['Embarked'].astype('category')

print('Tipos DESPUÉS de convertir:')
print(df[['Survived','Pclass','Sex','Embarked']].dtypes)

# Memoria DESPUÉS de convertir
memoria_despues = df.memory_usage(deep=True).sum() / 1024**2
ahorro = (1 - memoria_despues / memoria_antes) * 100

print(f'Memoria antes:  {memoria_antes:.3f} MB')
print(f'Memoria después: {memoria_despues:.3f} MB')
print(f'Ahorro: {ahorro:.1f}%')

# Ver categorías de las columnas category
print('Categorías de Sex:     ', df['Sex'].cat.categories.tolist())
print('Categorías de Pclass:  ', df['Pclass'].cat.categories.tolist())
print('Categorías de Embarked:', df['Embarked'].cat.categories.tolist())

"""### ✏️ Actividad 1: Comparar memoria

**Completá el código para responder:**

1. ¿Cuánto ahorro de memoria lograron las conversiones?
2. ¿Qué columna tenía el mayor tamaño antes de convertir?

```python
# TODO: Ver el uso de memoria POR COLUMNA antes y después
# Pista: df.memory_usage(deep=True)
```
"""

# TODO: Completá aquí
# Calculá el uso de memoria por columna y mostrá las 5 más pesadas
# Antes de las conversiones (si guardaste el df original) o después

memoria_por_col = df.memory_usage(deep=True).sort_values(ascending=False)
print('Top 5 columnas por memoria (bytes):')
print(memoria_por_col.head(6))  # head(6) porque la primera fila es el Index

"""---
## 📊 Sección 4: Estadística descriptiva

### 4.1 describe() — panorama completo
"""

# Estadísticas para columnas numéricas
df.describe()

# Estadísticas para columnas categóricas
df.describe(include=['category', 'object', 'bool'])

# Estadísticas detalladas solo para Age
print('=== Análisis de Age ===')
print(df['Age'].describe())
print()
print(f'Valores no nulos: {df["Age"].count()} de {len(df)}')
print(f'Valores nulos:    {df["Age"].isnull().sum()}')

"""### 4.2 Medidas de tendencia central y dispersión"""

# ─── TENDENCIA CENTRAL para Age ───
col = df['Age']

media   = col.mean()
mediana = col.median()
moda    = col.mode()[0]

print(f'Media:   {media:.2f}')
print(f'Mediana: {mediana:.2f}')
print(f'Moda:    {moda:.2f}')
print()
diferencia = abs(media - mediana)
print(f'Diferencia media-mediana: {diferencia:.2f}')
print('(Valor cercano a 0 indica distribución simétrica)')

# ─── DISPERSIÓN para Age ───
col = df['Age']

rango    = col.max() - col.min()
varianza = col.var()
std      = col.std()
Q1       = col.quantile(0.25)
Q3       = col.quantile(0.75)
IQR      = Q3 - Q1

print(f'Rango:    {rango:.2f}')
print(f'Varianza: {varianza:.2f}')
print(f'Std:      {std:.2f}')
print(f'Q1:       {Q1:.2f}')
print(f'Q3:       {Q3:.2f}')
print(f'IQR:      {IQR:.2f}')

# Estadísticas personalizadas para múltiples columnas
cols_num = ['Age', 'Fare', 'SibSp', 'Parch']
resumen = df[cols_num].agg(['mean', 'median', 'std', 'min', 'max']).round(2)
print('Resumen estadístico personalizado:')
print(resumen)

"""### ✏️ Actividad 2: Análisis de Fare

Calculá las mismas estadísticas para la columna `Fare`.

**Preguntas a responder:**
1. ¿La media es mayor, menor o igual a la mediana? ¿Qué indica eso?
2. ¿Es grande el desvío estándar comparado con la media?
3. ¿Cuánto vale el IQR?
"""

# TODO: Calculá media, mediana, moda, std, Q1, Q3 e IQR para 'Fare'
# Usá las mismas líneas de código que usamos para 'Age'

col_fare = df['Fare']

rango_fare    = col_fare.max() - col.min()
varianza_fare = col_fare.var()
media_fare    = col_fare.mean()
mediana_fare = col_fare.median()
std_fare      = col_fare.std()
Q1_fare       = col_fare.quantile(0.25)
Q3_fare       = col_fare.quantile(0.75)
IQR_fare      = Q3_fare - Q1_fare

print(f'Rango:    {rango_fare:.2f}')
print(f'Varianza: {varianza_fare:.2f}')
print(f'Std:      {std_fare:.2f}')
print(f'Q1:       {Q1_fare:.2f}')
print(f'Q3:       {Q3_fare:.2f}')
print(f'IQR:      {IQR_fare:.2f}')
print(f'Media Fare:   {media_fare:.2f}')
print(f'Mediana Fare: {mediana_fare:.2f}')

"""---
## 📈 Sección 5: Visualizaciones

### 5.1 Histograma de Age
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Histograma matplotlib ──
ax = axes[0]
ax.hist(df['Age'].dropna(), bins=20, color='steelblue', edgecolor='white', alpha=0.8)
ax.axvline(df['Age'].mean(),   color='tomato',  linestyle='--', lw=2, label=f'Media ({df["Age"].mean():.1f})')
ax.axvline(df['Age'].median(), color='orange',  linestyle='--', lw=2, label=f'Mediana ({df["Age"].median():.1f})')
ax.set_xlabel('Edad')  ;  ax.set_ylabel('Frecuencia')
ax.set_title('Distribución de edades — Titanic', fontweight='bold')
ax.legend()

# ── Histograma seaborn con KDE ──
sns.histplot(data=df, x='Age', bins=20, kde=True, color='steelblue', ax=axes[1])
axes[1].set_title('Age con KDE (densidad estimada)', fontweight='bold')
axes[1].set_xlabel('Edad')  ;  axes[1].set_ylabel('Frecuencia')

plt.tight_layout()
plt.show()

# Histograma de Fare — para observar el sesgo
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.histplot(data=df, x='Fare', bins=30, kde=True, color='mediumseagreen', ax=axes[0])
axes[0].axvline(df['Fare'].mean(),   color='tomato', linestyle='--', lw=2,
                label=f'Media ({df["Fare"].mean():.1f})')
axes[0].axvline(df['Fare'].median(), color='orange', linestyle='--', lw=2,
                label=f'Mediana ({df["Fare"].median():.1f})')
axes[0].set_title('Distribución de Fare (precio del pasaje)', fontweight='bold')
axes[0].legend()

# Escala logarítmica para ver mejor la distribución
df_fare = df[df['Fare'] > 0]
sns.histplot(data=df_fare, x='Fare', bins=30, kde=True,
             color='mediumseagreen', ax=axes[1], log_scale=True)
axes[1].set_title('Fare en escala logarítmica (mejor visualización)', fontweight='bold')

plt.tight_layout()
plt.show()

print('Observar: la diferencia entre media y mediana indica fuerte sesgo a la derecha.')

"""### 5.2 Boxplots"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Boxplot simple de Age ──
axes[0].boxplot(
    df['Age'].dropna(),
    patch_artist=True,
    boxprops=dict(facecolor='steelblue', alpha=0.7),
    medianprops=dict(color='tomato', lw=2),
    whiskerprops=dict(color='steelblue'),
    flierprops=dict(marker='o', color='gray', alpha=0.4, markersize=4)
)
axes[0].set_title('Boxplot de Age', fontweight='bold')
axes[0].set_ylabel('Edad')

# ── Boxplot de Age comparativo por sexo ──
sns.boxplot(data=df, x='Sex', y='Age',
            hue='Survived', palette='Set2', ax=axes[1])
axes[1].set_title('Age por Sexo y Supervivencia', fontweight='bold')

plt.tight_layout()
plt.show()

# Boxplot de Fare por clase de pasaje
plt.figure(figsize=(10, 5))
sns.boxplot(data=df, x='Pclass', y='Fare', palette='Blues')
plt.title('Distribución de precio del pasaje por clase', fontweight='bold')
plt.xlabel('Clase del pasaje')  ;  plt.ylabel('Fare (precio)')
plt.yscale('log')  # escala log para ver mejor la distribución
plt.tight_layout()
plt.show()

print('Los puntos fuera de los bigotes son outliers según la regla IQR.')

"""---
## 🚨 Sección 6: Detección de outliers con la regla del IQR

### Regla de Tukey
Un valor es **outlier** si cae fuera del rango:

$$[Q1 - 1.5 \times IQR, \quad Q3 + 1.5 \times IQR]$$
"""

def detectar_outliers(df, col):
    '''
    Detecta outliers usando la regla del IQR (metodo de Tukey).
    Retorna un DataFrame con los outliers encontrados.
    '''
    serie = df[col].dropna()
    Q1  = serie.quantile(0.25)
    Q3  = serie.quantile(0.75)
    IQR = Q3 - Q1
    lim_inf = Q1 - 1.5 * IQR
    lim_sup = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lim_inf) | (df[col] > lim_sup)]

    print(f'Columna: {col}')
    print(f'  Q1={Q1:.2f}  |  Q3={Q3:.2f}  |  IQR={IQR:.2f}')
    print(f'  Limite inferior: {lim_inf:.2f}')
    print(f'  Limite superior: {lim_sup:.2f}')
    print(f'  Outliers: {len(outliers)} ({len(outliers)/len(df)*100:.1f}% del dataset)')
    if len(outliers) > 0:
        print(f'  Valor maximo outlier: {df[col].max():.2f}')
        print(f'  Valor minimo outlier: {outliers[col].min():.2f}')
    print()
    return outliers

print('Funcion detectar_outliers() definida correctamente.')

# Aplicar a columna Age
outliers_age = detectar_outliers(df, 'Age')
print('Filas con outliers en Age:')
outliers_age[['Name', 'Age', 'Pclass', 'Survived']].head(10)

# Aplicar a columna Fare
outliers_fare = detectar_outliers(df, 'Fare')
print('Los pasajeros con pasaje mas caro (outliers de Fare):')
outliers_fare.nlargest(10, 'Fare')[['Name', 'Fare', 'Pclass', 'Survived']]

# Visualizar outliers en boxplot con anotaciones
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for ax, col, color in zip(axes, ['Age', 'Fare'], ['steelblue', 'mediumseagreen']):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lim_sup = Q3 + 1.5 * IQR

    sns.boxplot(data=df, y=col, color=color, ax=ax, flierprops={'alpha':0.3})
    ax.axhline(lim_sup, color='tomato', linestyle='--', lw=1.5,
               label=f'Limite superior ({lim_sup:.1f})')
    ax.set_title(f'Boxplot de {col} con limite IQR', fontweight='bold')
    ax.legend()

plt.tight_layout()
plt.show()

"""### ✏️ Actividad 3: Outliers en Fare

Usando la función `detectar_outliers()`, completá el siguiente análisis:

1. ¿Cuántos outliers tiene Fare? ¿Qué porcentaje del dataset representan?
2. ¿Cuál es el pasaje más caro? ¿A qué clase pertenece ese pasajero?
3. ¿Los outliers de Fare son errores de datos o casos legítimos? Justificá.

```python
# TODO: Investigar los outliers de Fare
# Pista: ordená outliers_fare por Fare de mayor a menor
# y mostrá Name, Fare, Pclass, Cabin, Survived
```
"""

# TODO: Completá este análisis
# Mostrar los 5 pasajeros con el pasaje más caro
# ¿Hay algo en común entre ellos? (clase, cabina, supervivencia)

outliers_fare_top5 = outliers_fare.nlargest(5, 'Fare')[['Name','Fare','Pclass','Cabin','Survived']]
print(outliers_fare_top5)

"""---
## 👥 Sección 7: Análisis por grupos con groupby()
"""

# Estadísticas de Age y Fare por clase de pasaje
print('Media de Age y Fare por Pclass:')
print(df.groupby('Pclass')[['Age', 'Fare']].mean().round(2))

# Tasa de supervivencia por sexo
surv_por_sexo = df.groupby('Sex')['Survived'].mean().round(3)
print('Tasa de supervivencia por sexo:')
print(surv_por_sexo)
print()
print('Interpretación: la proporción de 1s (True) en Survived')

# Tabla cruzada: supervivencia x sexo (porcentaje)
tabla = pd.crosstab(df['Sex'], df['Survived'], margins=True, normalize='index')
tabla.columns = ['No sobrevivió', 'Sobrevivió']
print('Tasa de supervivencia por sexo (%):')
print((tabla * 100).round(1))

# Estadísticas múltiples por grupo
resumen_clase = df.groupby('Pclass')['Age'].agg(
    ['mean', 'median', 'std', 'count']
).round(2)
resumen_clase.columns = ['Media', 'Mediana', 'Std', 'Count']
print('Estadísticas de Age por clase de pasaje:')
print(resumen_clase)

"""---
## 🎯 Actividad Integradora: Análisis completo de Fare

Realizá un análisis completo de la columna `Fare` siguiendo todos los pasos:

1. **Verificar tipo y nulos** — dtype, cuántos nulos hay
2. **Estadísticas manuales** — media, mediana, moda, std, IQR (sin usar describe)
3. **Histograma** — con líneas de media y mediana
4. **Boxplot comparativo** — por Pclass
5. **Outliers** — aplicar función detectar_outliers
6. **Conclusiones** — escribir al menos 3 observaciones en Markdown

---
"""

# PASO 1: Verificar tipo y nulos
# TODO: completar
print('Tipo de Fare:', df['Fare'].dtype)
print('Valores nulos:', df['Fare'].isnull().sum())

# PASO 2: Estadísticas manuales
# TODO: calcular media, mediana, moda, std, Q1, Q3, IQR para Fare
# (usar df['Fare'].mean(), etc.)

col_fare = df['Fare']
rango_fare    = col_fare.max() - col.min()
varianza_fare = col_fare.var()
media_fare    = col_fare.mean()
mediana_fare = col_fare.median()
std_fare      = col_fare.std()
Q1_fare       = col_fare.quantile(0.25)
Q3_fare       = col_fare.quantile(0.75)
IQR_fare      = Q3_fare - Q1_fare

print(f'Rango:    {rango_fare:.2f}')
print(f'Varianza: {varianza_fare:.2f}')
print(f'Std:      {std_fare:.2f}')
print(f'Q1:       {Q1_fare:.2f}')
print(f'Q3:       {Q3_fare:.2f}')
print(f'IQR:      {IQR_fare:.2f}')
print(f'Media Fare:   {media_fare:.2f}')
print(f'Mediana Fare: {mediana_fare:.2f}')
pass

# PASO 3: Histograma
# TODO: histograma de Fare con bins=30 y líneas de media y mediana

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Histograma matplotlib ──
ax = axes[0]
ax.hist(df['Fare'].dropna(), bins=30, color='steelblue', edgecolor='white', alpha=0.8)
ax.axvline(df['Fare'].mean(),   color='tomato',  linestyle='--', lw=2, label=f'Media ({df["Fare"].mean():.1f})')
ax.axvline(df['Fare'].median(), color='orange',  linestyle='--', lw=2, label=f'Mediana ({df["Fare"].median():.1f})')
ax.set_xlabel('Fare')  ;  ax.set_ylabel('Frecuencia')
ax.set_title('Distribución de Fare — Titanic', fontweight='bold')
ax.legend()

# ── Histograma seaborn con KDE ──
sns.histplot(data=df, x='Fare', bins=30, kde=True, color='steelblue', ax=axes[1])
axes[1].set_title('Fare con KDE (densidad estimada)', fontweight='bold')
axes[1].set_xlabel('Fare')  ;  axes[1].set_ylabel('Frecuencia')

plt.tight_layout()
plt.show()


pass

# PASO 4: Boxplot comparativo por Pclass
# TODO: boxplot de Fare agrupado por Pclass

# Boxplot de Fare por clase de pasaje
plt.figure(figsize=(10, 5))
sns.boxplot(data=df, x='Pclass', y='Fare', palette='Blues')
plt.title('Distribución de precio del pasaje por clase', fontweight='bold')
plt.xlabel('Clase del pasaje')  ;  plt.ylabel('Fare (precio)')
plt.yscale('log')  # escala log para ver mejor la distribución
plt.tight_layout()
plt.show()

print('Los puntos fuera de los bigotes son outliers según la regla IQR.')

pass

# PASO 5: Outliers
# TODO: aplicar detectar_outliers(df, 'Fare')

detectar_outliers(df, 'Fare')
pass

"""### PASO 6: Conclusiones

*Escribí aquí tus 3 observaciones sobre la distribución de Fare:*

1. Fare o Tarifas tienen un promedio de 32.5 pero una mediana de 14.5 lo que quiere decir que hay una gran concentración de datos en cuanto a tarifas de menos de "50"
2. El valor máximo de las tarifas registradas es de 512
3. El 13% del dataset supera los 116 sin embargo también encontramos valores necativos en el estudio de tarifas siendo el menor -26.72

---
## 📋 Resumen: Funciones clave del laboratorio

| Función | Qué hace |
|---------|----------|
| `df.dtypes` | Ver tipo de cada columna |
| `df.info()` | Resumen completo: tipos, no-nulos, memoria |
| `df.describe()` | Estadísticas descriptivas numéricas |
| `df.describe(include=['object'])` | Estadísticas para columnas textuales |
| `col.astype(tipo)` | Convertir tipo de columna |
| `col.mean()` / `.median()` / `.mode()` | Tendencia central |
| `col.std()` / `.var()` | Dispersión |
| `col.quantile(0.25)` / `(0.75)` | Cuartiles Q1 y Q3 |
| `col.isnull().sum()` | Contar valores nulos |
| `plt.hist()` / `sns.histplot()` | Histograma |
| `plt.boxplot()` / `sns.boxplot()` | Diagrama de caja |
| `df.groupby(col).agg(funcs)` | Estadísticas por grupos |
| `pd.crosstab(col1, col2)` | Tabla de contingencia |

---
**Próxima clase:** Unidad 3 — Análisis Exploratorio y Multivariado (EDA)
- Correlación entre variables (Pearson, Spearman)
- Heatmaps de correlación
- Pairplots y análisis bivariado
- Proceso sistemático de EDA

*Completar todas las actividades TODO antes de la próxima clase.*
"""