# -*- coding: utf-8 -*-
"""Alderete_Parcial_Aprendizaje_Automático.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s44aQ6Rk4I_oRwK6-kJfeqT90xvVvpO8

# Parcial de Aprendizaje Automático

## Alumno: Alderete Tomás

### Información General:

Este dataset proviene del Repositorio de Aprendizaje Automático de la Universidad de California, Irvine

### Dataset:

El dataset consta de información de pacientes egipcios que se sometieron a tratamientos con dosis para la VHC durante aproximadamente 18 meses.

### Información del Paciente:
- Edad
- Género
- IMC



### Síntomas:
- Fiebre
- Vomitos
- Dolor_Cabeza
- Diarrea
- Fatiga y Dolor de Huesos
- Ictericia
- Dolor de Abdomen

### Análisis, Estudios Médicos:

- Globulos Blancos               
- Globulos Rojos                 
- Hemoglobina                    
- Plaquetas                      
- Alamina_Aminotransferasa       
- ALT_Semana4                    
- ALT_Semana12                   
- ALT_Semana24                   
- ALT_Semana36                   
- ALT_Semana48                   
- RNA_Base                       
- RNA_Semana4                    
- RNA_Semana12                   

### Glosario:

- Globulos Blancos: Células del sistema inmunológico que defienden al cuerpo contra infecciones, virus y bacterias.

- Globulos Rojos: Células que transportan oxígeno desde los pulmones a todo el cuerpo y devuelven dióxido de carbono a los pulmones para ser exhalado

- Alamina Aminotransferesa (ALT): Es una enzima presente principalmente en el hígado. Niveles altos en sangre suelen indicar daño o inflamación hepática

- Ácido Ribonucleico (RNA): Molécula esencial que actúa como mensajero entre el ADN y la producción de proteínas. Nota: En análisis de sangre, a veces se confunde con la abreviatura de ARN, pero si te refieres a un marcador de laboratorio, podría ser un error tipográfico por RDW (ancho de distribución de glóbulos rojos) o RBC (recuento de glóbulos rojos), ya que el RNA no es un valor estándar en hemogramas comunes.

- Hemoglobina: Proteína dentro de los glóbulos rojos que contiene hierro y es la responsable de unirse al oxígeno y transportarlo por el cuerpo.

- Plaquetas (Trombocitos): Fragmentos celulares encargados de la coagulación de la sangre y la formación de coágulos para detener hemorragias.

Objetivos

1. (Clasificación) Crear un modelo de aprendizaje automático que pueda predecir si un paciente con Hepatitis C tiene, Ictericia, en base a los síntomas que presentan.

2. (Clasificación) Crear un modelo de aprendizaje automático que pueda predecir si un paciente se curó o no durante la Semana 12

## Modelos de Aprendizaje Automático a utilizar: Árbol de Decisión

## Librerías a Usar
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, recall_score, precision_score

"""## Analisis Exploratorio de Datos

### Dataset
"""

dat_csv = pd.read_csv ("HCV-Egy-Data.csv", encoding='ISO-8859-1' )
dat_csv.head()

"""### Tipos de Datos"""

# Inspeccionar los tipos de datos
print(dat_csv.dtypes)

"""Matriz de Correlación"""

# Correlación del Dataset
corr_matrix = dat_csv.corr()

# Tamaño en pulgadas
fig, ax = plt.subplots(figsize=(14, 12))

# sns.heatmap
sns.heatmap(corr_matrix,
            cmap="coolwarm",
            ax=ax,
            cbar=True,
            linewidths=.5)

plt.xticks(rotation=45, ha='right') # Rotar etiquetas
plt.yticks(rotation=0)
plt.title("Matriz de correlación", pad=20, fontsize=16)
plt.tight_layout()
plt.show()

"""### Resultado:

Como podemos ver, la mayoría de datos son enteros, algunos flotantes, voy a cambiar algunas de las columnas y transformarlos en tipo bool o modificar su salida, así como genero tiene de salida "1 y 2" siendo 1: Hombre, 2: Mujer. También voy a cambiar el nombre de las columnas y por ultimo eliminar las que no necesite para este estudio.

### Cambio de Nombres de las columnas:
"""

# Traducción al Español
español = ['Edad', 'Genero', 'IMC', 'Fiebre', 'Vomitos', 'Dolor_Cabeza', 'Diarrea', 'Fatiga_y_Dolor_Huesos', 'Ictericia', 'Dolor_Abdomen', 'Globulos_Blancos', 'Globulos_Rojos', 'Hemoglobina', 'Plaquetas', 'Aspartato_Aminotransferasa', 'Alamina_Aminotransferasa', 'ALT_Semana4', 'ALT_Semana12', 'ALT_Semana24', 'ALT_Semana36', 'ALT_Semana48', 'ALT_Semana_post24', 'RNA_Base', 'RNA_Semana4', 'RNA_Semana12', 'RNA_Final_Tratamiento', 'RNA_en_Finalización', 'Gradacion_Histologica_Basal', 'Estadificacion_Histologica_Basal']

df_español = dat_csv.rename(columns=dict(zip(dat_csv.columns, español)))
df_español.head()

# Descarto las columnas que no son necesarias
df_limpio =  df_español[["Edad", "Genero", "IMC", "Fiebre", "Vomitos", "Dolor_Cabeza", "Diarrea", "Fatiga_y_Dolor_Huesos", "Ictericia", "Dolor_Abdomen", "Globulos_Blancos", "Globulos_Rojos", "Hemoglobina", "Plaquetas", "Alamina_Aminotransferasa", "ALT_Semana4", "ALT_Semana12", "ALT_Semana24", "ALT_Semana36", "ALT_Semana48", "RNA_Base", "RNA_Semana4", "RNA_Semana12"]]

# Resultado en español y limpio
df_limpio.head()

"""### Transformar los tipos de datos"""

# Para evitar un error de Python hago una copia independiente del propio df_Limpio
if not isinstance(df_limpio, pd.DataFrame) or df_limpio._is_copy:
    df_limpio = df_limpio.copy()

# 1. Cambio de Género a tipo Categórico
df_limpio['Genero'] = df_limpio['Genero'].replace({1: 'Hombre', 2: 'Mujer'}).astype('category')

# 2. Cambios a tipo Bool (Sí/No -> True/False)
# 1=False (No), 2=True (Sí)

bool_mapping = {1: False, 2: True}
columnas_bool = [
    'Fiebre',
    'Vomitos',
    'Dolor_Cabeza',
    'Diarrea',
    'Fatiga_y_Dolor_Huesos',
    'Ictericia',
    'Dolor_Abdomen'
]

for col in columnas_bool:
    if col in df_limpio.columns:
        df_limpio[col] = df_limpio[col].replace(bool_mapping).astype('boolean')

# 3. Cambios a tipo Entero (Redondeo)
columnas_int = ['Plaquetas', 'ALT_Semana4', 'Globulos_Rojos']

for col in columnas_int:
    if col in df_limpio.columns:
        df_limpio[col] = df_limpio[col].round().astype('int64')

# Verificar los cambios
print("Tipos de datos actualizados:")
print(df_limpio.dtypes)
print("\nPrimeras filas:")
df_limpio.head()

"""### NULOS

"""

conteo_nulos = df_limpio.isnull().sum()
print(conteo_nulos)

"""Luego de realizar el estudio de datos, el siguiente paso es realizar los modelos de aprendizaje, y visualizaciones respectivas para al final llegar  conclusiones.

## EDA:

## Análisis Univariado

### Distribución de Edad
"""

plt.hist(df_limpio['Edad'], bins=29, alpha=0.7, edgecolor='k')
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.title('Distribución de Edad')
plt.show()

# Minimo de Edad y Máximo
min_edad = df_limpio['Edad'].min()
max_edad = df_limpio['Edad'].max()

print(f"Edad mínima: {min_edad}")
print(f"Edad máxima: {max_edad}")

"""### Distribución de los datos según el género del paciente"""

sns.countplot(x='Genero', data=df_limpio)
plt.xlabel('Género')
plt.ylabel('Frecuencia')
plt.title('Distribución de Género')
plt.show()

print(df_limpio['Genero'].value_counts())

"""OBJETIVO 1:

Predecir si un paciente va a tener el síntoma de Ictericia a partir de la información del paciente y de los síntomas del mismo
"""

# Copia del dataset
df_Objetivo = df_limpio.copy()

# Quitamos las variables que puedan perjudicar a la predicción de Ictericia
df_Objetivo = df_Objetivo.drop(['Genero', 'Globulos_Blancos', 'IMC', 'Hemoglobina', 'ALT_Semana4', 'ALT_Semana12', 'ALT_Semana36', 'ALT_Semana48', 'RNA_Base', 'RNA_Semana4', 'RNA_Semana12'], axis=1)

# Variable Objetivo a Predecir: Ictericia
X = df_Objetivo.drop('Ictericia', axis=1)
y = df_Objetivo['Ictericia']

# Entrenamiento y Testeo
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Creación del Arbol de Decisión
tree = DecisionTreeClassifier(criterion='gini', max_depth=8, random_state=42, class_weight='balanced')
tree.fit(X_train, y_train)

# Bajo el umbral o la "vara" para una mejor predicción
probabilidades = tree.predict_proba(X_test)[:, 1]
umbral = 0.3
y_pred_tree = tree.predict(X_test)
y_pred_ajustada = (probabilidades >= umbral).astype(int)

print("Métricas Árbol de Decisión:")
print(classification_report(y_test, y_pred_tree))
print(" ")
print(" ")
print(" ")
print(" ")

print("Métricas Árbol de Decisión Mejorado:")
print(classification_report(y_test, y_pred_ajustada))

# Disminuir los Falsos Negativos
print("Accuracy Árbol:", accuracy_score(y_test, y_pred_tree))
print("Accuracy Árbol Ajustado:", accuracy_score(y_test, y_pred_ajustada))

#
fig, ax = plt.subplots(1, 2, figsize=(12, 5))
sns.heatmap(confusion_matrix(y_test, y_pred_tree), annot=True, fmt="d", ax=ax[0], cmap="Blues")
ax[0].set_title("Matriz de Confusión Árbol de Decisión")

sns.heatmap(confusion_matrix(y_test, y_pred_ajustada), annot=True, fmt="d", ax=ax[1], cmap="Greens")
ax[1].set_title("Matriz de Confusión Árbol de Decisión ajustado")
plt.show()

"""## Prueba de Modelo en 500 pacientes nuevos"""

n_pacientes = 1500

# Generamos características aleatorias iniciales
data = {
    'Edad': np.random.randint(18, 80, n_pacientes),
    'Genero': np.random.choice(['M', 'F'], n_pacientes),
    'IMC': np.random.uniform(18, 35, n_pacientes),
    'Fiebre': np.random.choice([0, 1], n_pacientes, p=[0.6, 0.4]), # p = Probabulidad / es decir, 40% tiene fiebre
    'Vomitos': np.random.choice([0, 1], n_pacientes, p=[0.7, 0.3]),
    'Dolor_Cabeza': np.random.choice([0, 1], n_pacientes, p=[0.5, 0.5]),
    'Dolor_Abdomen': np.random.choice([0, 1], n_pacientes, p=[0.5, 0.5]),
    'Fatiga_y_Dolor_Huesos': np.random.choice([0, 1], n_pacientes, p=[0.5, 0.5]),
    'Diarrea': np.random.choice([0, 1], n_pacientes, p=[0.4, 0.6]),
    'Globulos_Blancos': np.random.randint(4, 12, n_pacientes),
    'Plaquetas': np.random.randint(150, 400, n_pacientes),
    'ALT_Base': np.random.randint(10, 800, n_pacientes)
}

df_falso = pd.DataFrame(data)

# REGLAS:
# Regla 1: Si ALT es muy alta (> 300), alta probabilidad de ictericia
# Regla 2: Si ALT es alta (> 200) Y hay fiebre, probabilidad media-alta
# Regla 3: Si ALT es alta (> 100) Y hay dolor abdominal, probabilidad media
# Regla 4: Si ALT es normal (< 100), muy baja probabilidad (a menos que haya otros síntomas graves)

y_ict = []

for i in range(n_pacientes):
    alt = df_falso.loc[i, 'ALT_Base']
    fiebre = df_falso.loc[i, 'Fiebre']
    dolor = df_falso.loc[i, 'Dolor_Abdomen']
    vomitos = df_falso.loc[i, 'Vomitos']

    prob = 0.0

    # Reglas de probabilidad
    if alt > 300:
        prob = 0.95                   # 95% ALT es muy alta
    elif alt > 200 and fiebre == 1:
        prob = 0.75                   # 75% ALT es muy alta y tiene fiebre
    elif alt > 100 and dolor == 1:
        prob = 0.60                   # 60% ALT es alta y tiene dolor
    elif alt > 100 and vomitos == 1:
        prob = 0.55                   # 55% ALT es alta y tiene vomitos
    elif alt > 150 and (fiebre == 1 or dolor == 1):
        prob = 0.50                   # 50% ALT es alta y tiene fiebre o dolor
    elif alt > 100:
        prob = 0.30                   # 30%
    else:
        prob = 0.05                   # Muy baja si ALT es normal

    # Convertir probabilidad a binario (0 o 1) con random
    if np.random.random() < prob:
        y_ict.append(1)
    else:
        y_ict.append(0)

# Columna con los datos recopilados
df_falso['Ictericia'] = y_ict

print("--- Estadísticas del Dataset Falso ---")
print(f"Total pacientes: {len(df_falso)}")
print(f"Pacientes con Ictericia (1): {df_falso['Ictericia'].sum()} ({df_falso['Ictericia'].mean():.2%})")
print(f"Rango ALT: {df_falso['ALT_Base'].min()} - {df_falso['ALT_Base'].max()}")

# Elimino las columnas que no son relevantes
columnas_a_eliminar = ['Genero', 'IMC', 'Globulos_Blancos', 'Plaquetas']
df_modelo = df_falso.drop(columns=columnas_a_eliminar)

X2 = df_modelo.drop('Ictericia', axis=1)
y2 = df_modelo['Ictericia']

# Variables de Entrenamiento
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.3, random_state=42)

# Entrenamiento del Árbol
tree = DecisionTreeClassifier(criterion='gini', max_depth=8, random_state=42, class_weight='balanced')
tree.fit(X_train2, y_train2)

# Predicción y Evaluación del Árbol
y_pred_std = tree.predict(X_test2)

print("\n--- Métricas con Umbral Estándar (0.5) ---")
print(classification_report(y_test2, y_pred_std))

# Predicción con umbral bajo (0.3) para maximizar Recall (Objetivo: Minimizar los Falsos Negativos)
probabilidades = tree.predict_proba(X_test2)[:, 1]
umbral_bajo = 0.3
y_pred_low = (probabilidades >= umbral_bajo).astype(int)


print(f"\n--- Métricas con Umbral Bajo ({umbral_bajo}) ---")
print(f"Recall (Sensibilidad): {recall_score(y_test2, y_pred_low):.4f}")
print(f"Precisión: {precision_score(y_test2, y_pred_low):.4f}")
print(classification_report(y_test2, y_pred_low))

# Reglas
print("\n--- Importancia de las Variables (Lo que el modelo aprendió) ---")
importances = tree.feature_importances_
feature_names = X2.columns
sorted_importances = sorted(zip(feature_names, importances), key=lambda x: x[1], reverse=True)
for name, score in sorted_importances:
    print(f"{name}: {score:.4f}")

# Visualización del Árbol

plt.figure(figsize=(20, 10))
plot_tree(tree, feature_names=X2.columns, class_names=['Sin Ictericia', 'Ictericia'], filled=True, rounded=True, fontsize=8)
plt.title("Árbol de Decisión: Predicción de Ictericia")
plt.show()

"""Objetivo 2

"""

# Copia del DataFrame
df_Objetivo2 = df_limpio.copy()

# Quitamos las variables luego de la semana12
df_Objetivo2 = df_Objetivo2.drop(['ALT_Semana24', 'ALT_Semana36', 'ALT_Semana48'], axis=1)

# Columna nueva a Predecir "Curado"
# Debemos detectar que en la Semana 12 no se encuntre virus, es decir, los valores de RNA en la Semana 12 deben de ser menores a 100
# Devuelve 0 si el valor es Mayor, es decir "No está curado"
# Devuelve 0 si el valor es Menor, es decir "Está curado"

df_Objetivo2['Curado'] = (df_Objetivo2['RNA_Semana12'] <= 100).astype(int)

X3 = df_Objetivo2.drop(['Curado', 'RNA_Semana12'], axis=1)
y3 = df_Objetivo2['Curado']

# One-hot encode the 'Genero' column
X3 = pd.get_dummies(X3, columns=['Genero'], drop_first=True)

# Entrenamiento y Testeo
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.3, random_state=42)

arbol_curacion = DecisionTreeClassifier(max_depth=7, random_state=42, class_weight='balanced')
arbol_curacion.fit(X_train3, y_train3)

# Predicción y Evaluación del Árbol
y_pred_std3 = arbol_curacion.predict(X_test3)

print("\n--- Métricas con Umbral Estándar (0.5) ---")
print(classification_report(y_test3, y_pred_std3))

# Visualización del Árbol
fig, ax = plt.subplots(figsize=(8, 6))
cm = confusion_matrix(y_test3, y_pred_std3)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax)
ax.set_title("Matriz de Confusión Árbol de Decisión", fontsize=14)
ax.set_xlabel("Predicción", fontsize=12)
ax.set_ylabel("Real", fontsize=12)

"""Conclusiónes

- **Precision (Precisión):** de los predichos por el modelo como positivos, cuántos lo son realmente.

En el objetivo 1 se puede observar que el modelo decía postivo, y había un 50 - 53% de los casos esto se cumplía.

En el segundo modelo, aplicando reglas encontramos una mejoría del modelo, empezó a relacionar mucho más los datos ficticios teniendo un 93% de acierto

En los casos de enfermos con ictericia, los detecta con mayor facilidad, sin embargo en casos de no enfermos, no es tan simple, se mantiene con un 61%

- **Recall (Sensibilidad):** de los positivos reales, cuántos fueron detectados.

En cuanto al recall, vemos que en ambos casos, en el primer modelo con la "vara", el modelo de aprendizaje detecta con mucha facilidad los enfermos pero tiene muchos problemas para detectar los sanos o curados, encontramos que aquellos pacientes que no tienen Ictericia, en uno de los modelos solamente pudo detectar el 18% de los casos, teniendo una gran cantidad de Falsos Negativos.

Sin embargo en el modelo de Prueba con 500 pacientes aleatorios, aplicando "Reglas", el modelo mejora llegando a 65% o incluso más

Por último, el objetivo principal es evitar los Falsos positivos que en ambos modelos encontramos que superan el 80% de los aciertos, siendo muy pocos de este mismo.

Por qué el interes en evitar esta medida?

Nuestro data set es sobre salud y la misma podemos relacionarla al evento diario de ir a una consulta en el hospital
Un Falso positivo se refiere al evento de un paciente ESTAR ENFERMO y el doctor detectar lo contrario, sería muy peligroso dejar pasar un caso así.


- **F1-score:** media armónica entre precisión y recall.

En el f1-score encontramos una media entre ambas, precisión y recall

- **Accuracy (Exactitud):** proporción de predicciones correctas.

El segundo modelo con las reglas correctas y los datos aleatorios, llegamos a un 82% de precisión, es un gran resultado

Por otro lado los resultados del Objetivo 2 son muy malos, casi peor que aleatorios, ya que el planteo del mismo no es el correcto para la tarea de predicción, o el uso de la información no es el adecuado.

El objetivo principal era poder predecir si un paciente se iba a curar durante la semana 12 teniendo la información del futuro o no (siendo también el objetivo 3, que tampoco se llevo a cabo)

El objetivo de estudiar este tipo de eventos era poder relacionar el tipo de información del paciente, plaquetas, globulos, con la información escencial que indicaba la existencia del virus.

Como sabemos:

RNA = Virus en sangre

ALT = Daño causado al hígado

No se podía predecir con la información ya que hay un evento muy común en la salud que impide esto.

Un paciente puede pasar de estar sano a enfermo durante un lapso de tiempo, o presentar cambios de sintomas o de la información antes mencionada, el ALT o RNA

Que cambios haría o Mejorías?

Quizá con un dataset más completo o con un mejor análisis conseguiría utilizar reglas para poder predecir este evento o mejorar la predicción

Pensé en la posibilidad de usar RandomForest, que es otra manera de estudiar los datos, sin embargo, consideré que es mejor estudiar la información en conjunto.

Por último, me ubiese gustado tener un caso de Regresión, o de agrupamiento, pensé en la posibilidad de agregar un K de 3 siendo 0 -  "Sano" / 1 - "Enfermo" / 2 - "Muy enfermo", pero los datos son muy complicados de estudiarlos, no hay muchas maneras de estudiar este escenario, y en base a diferentes tipos

Por ej:
Puedo basarme en la cantidad de sintomas
Las defensas, es decir, cuanto menor mayor el riesgo
El RNA o el ALT siendo el daño causado por la Hepatitis C.

Pero como sabemos tampoco hay una correlación entre los datos
Siendo esta ultima mi conclusión.

El OBJETIVO con este trabajo era llevarlo a la REALIDAD

Me gustaría plantear esta idea a un Hospital, pero teniendo diferentes reglas, diferente información, sé que soy un estudiante de IA pero podrían mejorarse e incluso con más información podríamos agregar columnas muy útiles

Este trabajo es en escencial de Hepatitis C

Pero la idea es poder identificar diferentes Enfermedades o 1 sola en particular con los diferentes sintomas con la mayor presición posible

En otras palabras mejoraríamos el tiempo de detección y tratamiento de las enfermedades que conocemos.
"""