# -*- coding: utf-8 -*-
"""AA_Clase4_Alderete_Tomás.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFgU7NryAinylU3ZHkxUEf_eHHDhRzkp

Actividad 1
Es importante que realices todas las actividades, estas te permitirán saber como vas avanzando y podrás reflexionar sobre la teoría si te queda alguna duda de cómo hacer esta actividad por favor consultanos en el campus.

El objetivo de esta actividad es encontrar un dataset de tu interés que contenga como variable objetivo una variable continua y aplicar la regresión lineal para intentar predecirla a partir de las demás variables predictoras.

El método que seguiremos es el siguiente:

●      Preparación y organización de datos

●      Exploración de los datos

●      Modelado de datos

Ahora seguimos adelante con un poco más de teoría que nos ayudará a andar en el tema.
"""

import pandas as pd
import numpy as np

# dat_csv = pd.read_csv('genz.csv', encoding = "ISO-8859-1")

# Voy a inventar un dataframe ya que genz contiene +10.000 registros y no encontré la forma de limitar la salida.
# La idea es utilizar columnas con la información similar, pero la conclusión no va a ser realista, como mencioné anteriormente, son datos inventados.

# PREPARACIÓN DE DATOS

# UN DATAFRAME CON 50 DATOS ALEATORIOS CON LAS COLUMNAS DE UN DATASET DE KAGGLE

n = 50
dat_csv = pd.DataFrame({
    "Edad": np.random.randint(18, 80, n),
    "Genero": np.random.choice(["Hombre", "Mujer"], n),
    "Hs_Diarias": np.random.uniform(0, 16, n),
    "Plataforma": np.random.choice(["Snapchat", "Youtube", "Instagram", "TikTok"], n),
    "Uso_Nocturno": np.random.choice([0, 1], n),
    "Nivel_Adiccion": np.random.choice(["Bajo", "Medio", "Alto"], n)
})

dat_csv.head()

import pandas as pd
import numpy as n

datos_x = dat_csv.Edad
datos_y = dat_csv.Hs_Diarias
x = []
y = []

# Converting Series to lists more efficiently
x = datos_x.tolist()
y = datos_y.tolist()

print(x)
print(y)

X = np.array(x)
Y = np.array(y)

# Calculo el 80% de entrenamiento y 20% de prueba
datos_entrenamiento = int(0.80 * len(X))
datos_prueba = len(X) - datos_entrenamiento

print(datos_entrenamiento)
print(datos_prueba)

# Datos de entrenamiento
X_entrenamiento = X[:datos_entrenamiento].reshape((datos_entrenamiento,1))
Y_entrenamiento = Y[:datos_entrenamiento].reshape((datos_entrenamiento,1))

# Datos de prueba
X_prueba = X[datos_entrenamiento:].reshape((datos_prueba,1))
Y_prueba = Y[datos_entrenamiento:].reshape((datos_prueba,1))


print(X_prueba)
print(Y_prueba)

from sklearn import linear_model

# Creamos un objeto de regresión lineal
linear_regressor = linear_model.LinearRegression()

# Ajustamos la regresión a los datos de entrenamiento
linear_regressor.fit(X_entrenamiento, Y_entrenamiento)

# Y a partir de datos de regresión encontrados
Y_predicha_de_entrenamiento = linear_regressor.predict(X_entrenamiento)

import matplotlib.pyplot as plt

plt.figure()
plt.scatter(X_entrenamiento, Y_entrenamiento, color='red')
plt.plot(X_entrenamiento, Y_predicha_de_entrenamiento, color='black', linewidth=2)
plt.title('Regresión Lineal')
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

"""Te proponemos entonces que realices ahora la siguiente actividad con los conceptos leídos anteriormente.

Para esta actividad se ha creado un archivo usuarios_win_mac_lin.csv con datos de entrada a modo de ejemplo para clasificar si el usuario que visita un sitio web usa como sistema operativo Windows, Macintosh o Linux.

Nuestra información de entrada son 4 características que se tomó de una web que utiliza Google Analytics y son:

●      Duración de la visita en Segundos

●      Cantidad de Páginas Vistas durante la Sesión

●      Cantidad de Acciones del usuario (click, scroll, uso de checkbox, sliders,etc)

●      Suma del Valor de las acciones (cada acción lleva asociada una valoración de importancia)

Como la salida es discreta, asignaremos los siguientes valores a las etiquetas:

0 – Windows

1 – Macintosh

2 -Linux

Tu tarea es crear una Jupyter Notebook Regresion_logistica.ipynb que permita predecir qué sistema operativo utiliza un usuario según los datos de entrada.

¿Cómo pudiste llevar adelante esta actividad? te pareció muy difícil o muy fácil?  ¿por qué?  Por favor compartí tu respuesta en el foro del Campus

Columnas del dataset:
- **id**: Cantidad de registros
- **duración**: Duración de la visita en Segundos
- **paginas**: Cantidad de Páginas Vistas durante la Sesión
- **acciones**:  Cantidad de Acciones del usuario (click, scroll, uso de checkbox, sliders,etc)
- **valor**: Suma del Valor de las acciones (cada acción lleva asociada una valoración de importancia)
- **clase**: la salida es discreta, asignaremos los siguientes valores a las etiquetas:

0 – Windows

1 – Macintosh

2 -Linux

# OBJETIVO: Crear un modelo que permita predecir qué sistema operativo utiliza un usuario según los datos de entrada.
"""

dat_csv = pd.read_csv('usuarios_win_mac_lin.csv', encoding = "ISO-8859-1")
dat_csv.head()

# dataset ficticio
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

# Convertir variables categóricas en variables dummies (0/1)
usu_encoded = pd.get_dummies(dat_csv, drop_first=True)

# Separamos las variables predictoras (X) y la variable objetivo (y)
X_adiccion = usu_encoded.drop("clase", axis=1)
y_adiccion = usu_encoded["clase"]

# 25% de prueba y 75% de entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X_adiccion, y_adiccion, test_size=0.25, random_state=42)

# Creamos el modelo de regresión logística binaria
log_reg_binaria = LogisticRegression(max_iter=1000)
log_reg_binaria.fit(X_train, y_train)

# Predicciones en el conjunto de prueba
y_pred_usu = log_reg_binaria.predict(X_test)

# Matriz de confusión para comparar valores reales vs predicciones
cm_usu = confusion_matrix(y_test, y_pred_usu)
plt.figure(figsize=(6,4))
sns.heatmap(cm_usu, annot=True, fmt="d", cmap="Blues", xticklabels=[0, 1, 2], yticklabels=[0, 1, 2])
plt.title("Matriz de confusión - Nivel de Adicción")
plt.ylabel("Valor real")
plt.xlabel("Predicción")
plt.show()
print(classification_report(y_test, y_pred_usu))

"""¿Cómo pudiste llevar adelante esta actividad? te pareció muy difícil o muy fácil?  ¿por qué?  Por favor compartí tu respuesta en el foro del Campus

Los ultimos temas, tanto de Minería de Datos como Aprendizaje Automático, me parecieron muy dificiles, quizá es porque tengo un nivel de programación muy bajo, pero suelo usar mucha IA para entender que es lo que estoy haciendo, intentar comprender que es lo que escribo o de donde sale, que es lo que cambia cada parte del código y luego intento realizarlo sin ayuda.

En el primer ejercicio utilicé datos inventados, llegando a una conclusión que puede variar, ya que no encontré una base de datos modelo con menos de 100 registros, busque en Kaggle y solo conseguí de más de 1000 lo que relentiza el proceso. Mi idea era crear un DataFrame con datos aleatorios, solo para poder observar el código y la visualización de los datos

Tengo dudas en este ejercicio, ¿Cómo hago para poder mejorar la calidad del gráfico cuando tengo muchos registros?
En mi primer intento utilicé una base de datos de 10.000 registros y no se podía observar correctamente, a mi parecer, se veía manchado, no encontraba donde hay mayor concentración de registros ya que en todos lados pasaba esta situación.

En el segundo ejercicio copie y seguí a la par el notebook de ejemplo, con los datos de el csv propuesto, conseguí un 70% de acierto en la predición, a mi parecer muy alto y un porcentaje muy positivo pensando en que hay 3 variables, lo que indica que utilizar el Azar para elegir, solo nos dejaría con un 33% de acierto.


"""