# -*- coding: utf-8 -*-
"""Clase 4 Teoria de Mineria de Datos - Alderete Tomás.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwzKBIeHAMOG20pfNO2dBLD3WY7aRGu4

Ejercicio para la Sección 1
Objetivo: Practicar la selección de gráficos según el tipo de análisis.

- Comparar el salario promedio en diferentes industrias.

- Analizar si existe una relación entre la cantidad de horas trabajadas y el nivel de productividad.

- Detectar valores atípicos en los montos de transacciones bancarias.


- Observar la distribución de notas de un curso.

Explica por qué elegiste cada tipo de gráfico.


Si tienes conocimientos en Python, escribe un código utilizando Seaborn para
visualizar alguno de los casos.

RTA:

1 - Para el primer caso utilizaría un boxplot multiple, en el mismo podríamos observar la media, la moda de cada industria por separado, personalmente es más visual que los datos en un diagrama de distribución separado por categoría, tiene el mismo efecto sin embargo visualmente es mejor el antes mencionado en caso de tener una gran cantidad de registros.

2 - Al querer saber si existe una relación podría hacer un mapa de correlación entre ambas variables.

3 - Utilizaría el Boxplot individual para los valores atípicos, e intentaría además de los graficos realizar un estudios de los datos.

4 - Como quiero observar la distribución utilizaría un Histograma con la variable de "notas", lo mismo me permitiría saber la cantidad de registros que se encuentran con dicho valor.

Ejemplo en Python – Diferentes Tipos de Visualización
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Crear datos
df = pd.DataFrame({
    "Edad":      [25, 32, 40, 35, 50, 45, 29, 37, 41, 60],
    "Ingresos":  [30000, 45000, 60000, 55000, 80000, 75000, 40000, 58000, 72000, 90000],
    "Categoría": ["Joven", "Adulto", "Adulto", "Adulto", "Senior", "Senior", "Joven", "Adulto", "Adulto", "Senior"]
})

# Histograma de edades
sns.histplot(df["Edad"], bins=5, kde=True)
plt.title("Distribución de Edades")
plt.show()

# Boxplot de ingresos
sns.boxplot(x=df["Ingresos"])
plt.title("Boxplot de Ingresos")
plt.show()

# Scatter Plot entre Edad e Ingresos
sns.scatterplot(x=df["Edad"], y=df["Ingresos"], hue=df["Categoría"])
plt.title("Relación entre Edad e Ingresos")
plt.show()

"""Conclusión: Seaborn es ideal para gráficos estadísticos más complejos, como histogramas con KDE, boxplots y pairplots.

Ejercicio para la Sección 2

Objetivo: Practicar el uso de Matplotlib y Seaborn creando gráficos de distintos tipos.

Instrucciones:

Usa Matplotlib para crear un gráfico de barras que muestre el promedio de

ingresos de diferentes categorías de empleados.

Usa Seaborn para crear un scatterplot que muestre la relación entre Edad e
Ingresos en un dataset de empleados.

Explica cuál de los dos gráficos es más fácil de interpretar y por qué.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Crear DataFrame
df = pd.DataFrame({
    "Categoría":        ["Junior", "Semi-Senior", "Senior"],
    "Salario_Promedio": [35000, 60000, 90000]
})

# Gráfico de barras con Matplotlib
plt.bar(df["Categoría"], df["Salario_Promedio"], color=["blue", "green", "red"])
plt.xlabel("Categoría de Empleado")
plt.ylabel("Salario Promedio")
plt.title("Salario Promedio por Categoría")
plt.show()

# Crear DataFrame con edades e ingresos
df2 = pd.DataFrame({
    "Edad":     [25, 32, 40, 35, 50, 45, 29, 37, 41, 60],
    "Ingresos": [30000, 45000, 60000, 55000, 80000, 75000, 40000, 58000, 72000, 90000]
})

# Scatterplot con Seaborn
sns.scatterplot(x=df2["Edad"], y=df2["Ingresos"])
plt.title("Relación entre Edad e Ingresos")
plt.show()

"""**Preguntas de Reflexión**

**¿Cuál de los dos gráficos te parece más útil para analizar la información? **


Creo que los dos gráficos son interesantes para analizar, el primero separa en categorías como el título del empleado, siendo Junior, Semi-Senior y Senior, mientras que el segundo lo realiza por la edad.

Ambos aportan información valiosa, con el primero sabemos que un titulo más alto tiene mayores ingresos, mientras que con el segundo vemos que personas de mayor edad tienen también un mayor ingreso a comparación de más jovenes.

Personalmente me gustaría saber si todos los senior son los mayores de edad, ya que pienso en el escenario de alguien que no quiera llegar a serlo, y se quede en junior o semi-senior. Por último saber que es lo que hace a alguien "Senior", es decir, ¿La experiencia, el tiempo?, por supuesto es un titulo que se adquiere con el conocimiento pero lo mismo debe de ser representativo con los datos estudiados

**¿Cómo podría mejorarse la interpretación de estos gráficos?**

Yo creo que los graficos deben de ser sencillos para el estudio, utilizar colores para separar por categoría es una buena idea, también debemos de entender que es lo que estamos queriendo estudiar, como en el primer ejercicio mencione al grafico de boxplot multiple que personalmente es  muy util para observar todo, comparar las variables, ver la media de cada una de estar así como los valores atipicos.



**¿Cómo podrías aplicar esto en un dataset real?**

Al ser pocos registros podríamos separar el segundo grafico en colores representados por categoría, sin embargo si estos son muchos ya pasaríamos a tener un grafico manchado en el cual la información es dificil de observar e interpretar, en dado caso recomendaría el primero o

Instrucciones:

Selecciona el gráfico adecuado para cada uno de los siguientes análisis:

Comparar el salario promedio en diferentes industrias.

Analizar si existe una relación entre la cantidad de horas trabajadas y el nivel de productividad.

Detectar valores atípicos en los montos de transacciones bancarias.
Observar la distribución de notas de un curso.

Explica por qué elegiste cada tipo de gráfico.

Si tienes conocimientos en Python, escribe un código utilizando Seaborn para visualizar alguno de los casos.

Ejemplo en Python – Crear un gráfico de líneas con Matplotlib
"""

import matplotlib.pyplot as plt

# Datos de ejemplo
x = [1, 2, 3, 4, 5]
y = [10, 20, 25, 30, 50]

# Crear gráfico de líneas
plt.plot(x, y, marker='o', linestyle='-', color='b', label="Crecimiento")
plt.xlabel("Tiempo")
plt.ylabel("Valor")
plt.title("Ejemplo de Gráfico de Líneas")
plt.legend()
plt.show()

"""Ejemplo en Python – Histogramas y Boxplots con Seaborn"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Crear un DataFrame con datos ficticios
df = pd.DataFrame({
    "Edad":     [25, 32, 40, 35, 50, 45, 29, 37, 41, 60],
    "Ingresos": [30000, 45000, 60000, 55000, 80000, 75000, 40000, 58000, 72000, 90000]
})

# Histograma de edades
sns.histplot(df["Edad"], bins=5, kde=True)
plt.title("Distribución de Edades")
plt.show()

# Boxplot de ingresos
sns.boxplot(x=df["Ingresos"])
plt.title("Boxplot de Ingresos")
plt.show()

"""Objetivo: Practicar el uso de Matplotlib y Seaborn creando gráficos de distintos tipos.


Instrucciones:

Usa Matplotlib para crear un gráfico de barras que muestre el promedio de ingresos de diferentes categorías de empleados.

Usa Seaborn para crear un scatterplot que muestre la relación entre Edad e Ingresos en un dataset de empleados.

Explica cuál de los dos gráficos es más fácil de interpretar y por qué.
"""

# Matplotlib
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.DataFrame({
    "Categoría":        ["Junior", "Semi-Senior", "Senior"],
    "Salario_Promedio": [35000, 60000, 90000]
})


# Gráfico de barras con matplotlib
plt.bar(df["Categoría"], df["Salario_Promedio"])
plt.xlabel("Categoría de empleado")
plt.ylabel("Salario promedio")
plt.title("Salario promedio por categoría")
plt.show()

# Crear DataFrame con edades e ingresos
df2 = pd.DataFrame({
    "Edad":     [25, 32, 40, 35, 50, 45, 29, 37, 41, 60],
    "Ingresos": [30000, 45000, 60000, 55000, 80000, 75000, 40000, 58000, 72000, 90000]
})

# Scatterplot con Seaborn
sns.scatterplot(x=df2["Edad"], y=df2["Ingresos"])
plt.title("Relación entre Edad e Ingresos")
plt.show()

"""1 - Me parece más útil el 2do gráfico pero con las separaciones de las categorias senior, junior y semi-senior de esta forma podemos observar 3 graficos en 1, podemos comparar los ingresos, las edades, y los titulos que tienen los empleados en cuanto a sus edades.

2 - yo creo que podría mejorarse dependiendo de la pregunta planteada, el primer gráfico personalmente se puede mejorar separando las columnas en 3 colores diferentes, algo más visual y representativo, el 2do podríamos hacer un diagrama de correlación y graficar una recta en la que se represente que hay una relación entre la edad y los ingresos.

3 - Creo que podría aplicar esto en un dataset real identificando correctamente las variales.

Ejemplo en Python – Pairplot con Seaborn
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Cargar dataset de pingüinos de Seaborn
df = sns.load_dataset("penguins")

# Crear Pairplot
sns.pairplot(df, hue="species", diag_kind="kde")
plt.show()

"""Ejemplo en Python – Heatmap de correlaciones


"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Cargar dataset
df = sns.load_dataset("penguins").dropna()

# Calcular matriz de correlación
correlaciones = df.corr(numeric_only=True)

# Crear Heatmap
sns.heatmap(correlaciones, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Mapa de Correlación entre Variables")
plt.show()

"""Ejemplo en Python – Violin Plot"""

import seaborn as sns
import matplotlib.pyplot as plt

# Cargar dataset
df = sns.load_dataset("penguins")

# Crear Violin Plot
sns.violinplot(x="species", y="bill_length_mm", data=df, palette="muted")
plt.title("Distribución del Largo del Pico por Especie")
plt.show()

"""Ejercicio para la Sección 3

Objetivo: Aplicar gráficos avanzados para extraer insights de un dataset.

Instrucciones:

Carga el dataset de diamantes de Seaborn (diamonds).

Crea un Pairplot para analizar la relación entre precio, quilates y profundidad.

Genera un Heatmap para visualizar la correlación entre las variables numéricas.

Crea un Violin Plot para comparar la distribución del precio en cada categoría de corte (cut).

Escribe una conclusión basada en los gráficos
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Cargar dataset
df = sns.load_dataset("diamonds")

# 1. Pairplot entre precio, quilates y profundidad
sns.pairplot(df[["price", "carat", "depth"]])
plt.show()

# 2. Heatmap de correlaciones
correlaciones = df.corr(numeric_only=True)
sns.heatmap(correlaciones, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Mapa de Correlación de Diamantes")
plt.show()

# 3. Violin Plot para comparar precio según corte
sns.violinplot(x="cut", y="price", data=df, palette="muted")
plt.title("Distribución del Precio por Tipo de Corte")
plt.show()

"""¿Qué variables están más correlacionadas con el precio?

Observando el Mapa de correlación de Diamantes, podemos observar que las variables: carat "quilates" y las dimensiones de los diamantes "x, y, z" están altamente corelacionadas positivamente con el precio, es decir que cuando aumenta alguna de las variables mencionadas, aumenta la otra.


¿Cómo varía la distribución del precio en los diferentes tipos de corte?

Podemos ver que en el gráfico de Boxplot Multiple hay una gran concentración de los datos en todos los casos, pero podemos observar que el corte "Ideal" hay una concentración en precios más bajos a comparación de las demás variables que tienen una disperción un poco mayor, sin embargo vemos como todas las variables en algún registro consiguen alcanzar los valores más altos llegando a casi 20.000, en este sentido ninguna variable destaca.

¿Qué otros insights puedes extraer de estos gráficos?

Podemos observar la linea blanca en los Boxplot Multiples lo que nos indica la media y entre los cortes vemos que el corte "Fair" presenta una mayor media en comparación al resto, es decir tiende a tener un precio más elevado que el resto.

**Actividad Obligatoria**

Tareas a realizar


Análisis Exploratorio de Datos (EDA)

- Generar histogramas para Edad e Ingresos.

- Crear un boxplot para visualizar valores atípicos en Compras.

- Generar un scatter plot para analizar la relación entre Ingresos y Compras.

Visualización Avanzada

- Crear un Pairplot con las variables numéricas.

- Generar un Heatmap de correlaciones entre todas las variables numéricas.

- Utilizar un Violin Plot para comparar la distribución de Compras según la Categoría.

Interacción con una Herramienta de IA (LLM)

- Hacer una consulta a ChatGPT, Gemini u otra herramienta LLM para obtener insights sobre los datos.

- Ejemplo de consulta: "Tengo un dataset con datos de clientes (edad, ingresos y número de compras). ¿Qué visualizaciones me recomendarías para encontrar patrones?"

- Comparar la respuesta con lo aprendido en la clase y reflexionar sobre su utilidad.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Crear DataFrame
df = pd.DataFrame({
    "Cliente":   [1, 2, 3, 4, 5, 6, 7, 8],
    "Edad":      [25, 40, 35, 50, 30, 45, 38, 29],
    "Ingresos":  [50000, 60000, 70000, 80000, 45000, 85000, 72000, 48000],
    "Compras":   [5, 15, 10, 20, 7, 18, 12, 6],
    "Categoría": ["A", "B", "C", "A", "B", "C", "A", "B"]
})

# 1) Análisis Exploratorio
sns.histplot(df["Edad"], bins=5, kde=True)
plt.title("Distribución de Edades")
plt.show()

sns.boxplot(x=df["Compras"])
plt.title("Boxplot de Compras")
plt.show()

sns.scatterplot(x=df["Ingresos"], y=df["Compras"])
plt.title("Relación entre Ingresos y Compras")
plt.show()

# 2) Visualización Avanzada
sns.pairplot(df[["Edad", "Ingresos", "Compras"]])
plt.show()

# Mapa de calor de correlaciones
correlaciones = df.corr(numeric_only=True)
sns.heatmap(correlaciones, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Mapa de Correlación de Variables")
plt.show()

# Violin Plot de Compras por Categoría
sns.violinplot(x="Categoría", y="Compras", data=df, palette="muted")
plt.title("Distribución de Compras por Categoría")
plt.show()

"""# Actividad Obligatoria

Entregarla en el espacio para la misma dentro del Campus.

**Objetivo**: Aplicar todas las técnicas de visualización de datos vistas en la clase para analizar un dataset real y compartir los hallazgos en el foro.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# DataFrame importado desde Kaggle.
dat_csv = pd.read_csv('Teen_Mental_Health_Dataset.csv', encoding = "ISO-8859-1")
dat_csv_pequeño = dat_csv.head(100)

dat_csv_pequeño.head(101) # Comprobación que hay solo 100 registros

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1) Análisis Exploratorio
sns.histplot(dat_csv_pequeño["age"], bins=5, kde=True)
plt.title("Distribución de Edades")
plt.show()

sns.boxplot(x=dat_csv_pequeño["sleep_hours"])
plt.title("Boxplot de horas de sueño")
plt.show()

sns.scatterplot(x=dat_csv_pequeño["daily_social_media_hours"], y=dat_csv_pequeño["academic_performance"])
plt.title("Relación entre horas de redes sociales y promedio academico")
plt.show()

# 2) Visualización Avanzada
sns.pairplot(dat_csv_pequeño[["sleep_hours", "daily_social_media_hours", "academic_performance"]])
plt.show()

# Mapa de calor de correlaciones
correlaciones = dat_csv_pequeño.corr(numeric_only=True)
sns.heatmap(correlaciones, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Mapa de Correlación de Variables")
plt.show()

# Violin Plot de Compras por Categoría
sns.violinplot(x="gender", y="screen_time_before_sleep", data=dat_csv_pequeño, palette="muted")
plt.title("Distribución de horas de pantalla antes de dormir por genero")
plt.show()

"""Luego de realizar un análisis de la salud mental en jovenes que tienen adiccion a las redes sociales, una base de datos encontrada en Kaggle en la que solo tomé una parte de la base de datos para el estudio, encontré que no hay una correlación entre los datos.

Como podemos observar en los gráficos lo primero que observe fueron registros de que edades encontramos, en lo que destaca la edad de 13 años por sobre las demás.

Luego cree un BoxPlot para observar las horas de sueño que tenían los jovenes y buscar la media, siendo la misma muy baja, encontré que la media es de 6 hs de sueño mientras que los valores típicos rondan entre las 5 y 7 horas y media, esto quiere decir que es menos de lo recomendado "8 horas", también encontramos registros de jovenes que duermen 4 horas que puede llegar a ser preocupante y dañino para la salud si se repite durante varias noches.

Luego busque comparar las horas de redes sociales con el rendimiento academico de los jóvenes y no encontré una correlación.
Después busque si existía alguna correlacion entre los datos, y en el mapa de correlaciones no encontré ninguna positiva o negativa.

Por último comparé las horas de uso de celular antes de dormir por genero, pero tampoco encontré una diferencia, los datos representados son similares a los estudiados en el BoxPlot.

Consulta a ChatGPT

" Tengo un dataset con datos de clientes (edad, ingresos y número de compras). ¿Qué visualizaciones me recomendarías para encontrar patrones "

RTA:
La IA me recomienda los graficos:

1. Scatter Plot (gráfico de dispersión)
- Correlaciones,
- Grupos de clientes,
- Clientes atípicos.


2. Boxplot
- Detectar outliers,
- Comparar distribuciones.

3. Histogramas:
- Cómo se distribuyen los datos,
- Si hay concentraciones,
- Si los datos están equilibrados.

4. Heatmap de correlación
- Si ingresos y compras están relacionados,
- Qué variables tienen más influencia.

5. Pairplot
- Scatterplots entre variables,
- Histogramas,
- Relaciones generales.


En comparación con lo aprendido en clase la IA sugirió los mismos graficos que estudiamos a lo largo de esta clase, también agregó información sobre por qué utilizaría cada uno, es decir que se puede observar.
"""